### ISSUE TITLE
plt.show() for visualisation

### ISSUE THREAD

**Issue by hareyakana** [johannfaouzi/pyts#1]
I was trying this python library on my mac and notice that during visualisation from this library, it does not automatically show the plot unless I explicitly show it. I think it would be a nice feature that it automatically show the plot when I use the visualisation features. It is probably as simple as adding `plt.show()` at the end.

**Comment by johannfaouzi** [comment]
You're right, I mainly tried out my code with notebooks and the magic command %matplotlib inline. My bad. I'm going to fix that ASAP.

**Comment by hareyakana** [comment]
thank you for your effort. this library has make some of my efforts a bit easier(do not need to code it from ground up). Hope that it receive more attention as time passes.
