### ISSUE TITLE
question about the diagonal line of RP plots

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [johannfaouzi/pyts#129]
My recurrence plots all have a diagonal from the top left to bottom right. This is contrary to the examples provided in the documentation which run from bottom left to top right. Am I doing something wrong or does this depend on the data? 

![20200101 1240](https://user-images.githubusercontent.com/5278928/168493491-bf69bc9a-046a-499d-b91b-cb0d3a90a502.png)

**Comment by johannfaouzi** [comment]
It's just a visualisation issue, whether the origin is at the upper left (your case) or at the lower left (like in this [example](https://pyts.readthedocs.io/en/stable/auto_examples/image/plot_single_rp.html#sphx-glr-auto-examples-image-plot-single-rp-py)). You can change this setting using the `origin` parameter in matplotlib.pyplot.imshow().

**Comment by Karlheinzniebuhr** [comment]
thanks much!
