### ISSUE TITLE
The pip package needs to be updated

### ISSUE THREAD

**Issue by ganyeshprasanna** [johannfaouzi/pyts#13]
There is an error in the code corresponding to MTF that results in a shape mismatch whenever it is run. I believe that the repository is up to date and the error has been corrected and it seems to work fine. The MTF in the pip package however does not work and it needs to be updated. Changing the image.py works just fine, but it does not work right out the box.
Great package overall, thanks. :D

**Comment by johannfaouzi** [comment]
Thank you for the report. I just uploaded the current version of master on PyPI, so it should be fixed.
Thanks for the kind words.
