### ISSUE TITLE
plot_ssa.py example fails on 0.7.0

### ISSUE THREAD

**Issue by willw1** [johannfaouzi/pyts#14]
ValueError: could not broadcast input array from shape (48) into shape (1)

(both from the pip package and git)

Very useful toolbox, thanks.

**Comment by johannfaouzi** [comment]
Hi,

Could you give me more details (the full traceback for instance)? Did you run the example without any modifications? I just ran it and it works for me. It also worked when building the documentation (see [here](https://pyts.readthedocs.io/en/latest/auto_examples/plot_ssa.html#sphx-glr-auto-examples-plot-ssa-py)). Looking at the error, I'd guess that it comes from the "grouping" phase of the algorithm, but it is a bit hard to know why you get this error without the full traceback.

Best regards,
Johann

**Comment by willw1** [comment]
I ran it without modifications, just copied and pasted it into ipython. Running on anaconda python 2.7.15, with numpy 1.11.1 and sklearn 0.17.1

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-a0e0ad01778f> in <module>()
     23 grouping = [[0, 1]]
     24 ssa = SSA(window_size, grouping)
---> 25 X_ssa = ssa.fit_transform(X)
     26 
     27 # Show the results for the first time series

/home/is/wwoods/sklearn/base.pyc in fit_transform(self, X, y, **fit_params)
    453         if y is None:
    454             # fit method of arity 1 (unsupervised transformation)
--> 455             return self.fit(X, **fit_params).transform(X)
    456         else:
    457             # fit method of arity 2 (supervised transformation)

/home/is/wwoods/.local/lib/python2.7/site-packages/pyts/decomposition/decomposition.pyc in transform(self, X)
    101 
    102         return np.apply_along_axis(self._ssa, 1, X, n_features,
--> 103                                    self.window_size, self.grouping)
    104 
    105     def _ssa(self, ts, ts_size, window_size, grouping):

/usr/local/anaconda2/lib/python2.7/site-packages/numpy/lib/shape_base.pyc in apply_along_axis(func1d, axis, arr, *args, **kwargs)
    115         outshape[axis] = len(res)
    116         outarr = zeros(outshape, asarray(res).dtype)
--> 117         outarr[tuple(i.tolist())] = res
    118         k = 1
    119         while k < Ntot:

ValueError: could not broadcast input array from shape (48) into shape (1)

**Comment by johannfaouzi** [comment]
It looks like this code is not compatible with this version of numpy (1.11.1). I have the same error with numpy==1.11.1 but have None with numpy==1.13.3.

Looking at the [changelog for the release of 1.13 of numpy](https://docs.scipy.org/doc/numpy-1.13.0/release.html), it seems that it is the first version that have **support for returning arrays of arbitrary dimensions in apply_along_axis**:

> Previously, only scalars or 1D arrays could be returned by the function passed to apply_along_axis. Now, it can return an array of any dimensionality (including 0D), and the shape of this array replaces the axis of the array being iterated over.

In my code, the function passed to apply_along_axis returns a 2D array.

The section "Dependencies" of the README.md is wrong, I'm going to update it. But in the mean time, I'm working on speed up all the code with numba, so this restriction may not be needed in future releases.

If you can update your version of numpy, that would address the issue.
