### ISSUE TITLE
Docs: What do colours/squares of MTF mean?

### ISSUE THREAD

**Issue by mohataher** [johannfaouzi/pyts#19]
Reading the docs, it appears that it may not have any explanation for the colours and square values inside the MTF image ?  Do you think this info is worth adding?

**Comment by johannfaouzi** [comment]
The values of the squares are just number between -1 and 1, and the colors depend on which colormap one chooses. In the examples, the colormap is set to 'rainbow'. A [colorbar](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.colorbar.html) could definitely be added to show which colors correspond to which values. Concerning the values, I would need to read the paper over to have a precise idea.

I agree that the docstrings of almost all the classes could be better (give a small explanation about the algorithm, add the reference, etc.). I don't think that it will be perfect but I will strive myself to make them better for the next release.
