### ISSUE TITLE
Inquiry about Window sliding in WEASEL

### ISSUE THREAD

**Issue by shc443** [johannfaouzi/pyts#25]
#### Description

Thank you for your contribution to implementing this awesome algo! 
I was working on your WEASEL code, but I just figured out that the windowing is not overlapping. Do you mind if I ask you why?

#### Steps/Code to Reproduce

```python
windowed_view(X,12,12)[0]

```

**Comment by johannfaouzi** [comment]
Hi,

In the original paper, [Fast and Accurate Time Series Classification with WEASEL](https://www2.informatik.hu-berlin.de/~schaefpa/weasel.pdf), page 6, it is mentioned that non-overlapping windows are used:

> The ANOVA F-test further assumes that the samples are independently drawn. To guarantee independence, we are extracting disjointsubsequences, i.e., non-overlapping, to train the quantization intervals.  Using disjoint windows for sampling further decreases thelikelihood of over-fitting quantization intervals.

Regarding the implementation in pyts, you have the choice through the `window_steps` parameter: you can set it to `None` (default value) to have non-overlapping windows, or you can provide an array-like (for instance an array of ones, with the same length as `window_sizes`, if you want a step of length 1). You can find more information on the parameters in the [API documentation](https://pyts.readthedocs.io/en/latest/generated/pyts.transformation.WEASEL.html#pyts.transformation.WEASEL).

I hope that it helps! Feel free to ask more questions :)

**Comment by shc443** [comment]
Thank you so much!  Hope you have a great day
