### ISSUE TITLE
How to perform inverse_transform on GAF transformed time series

### ISSUE THREAD

**Issue by Porosh014** [johannfaouzi/pyts#34]
I am using Gramain Angular Transformation to encode my time series data into images. For some reconstruction purpose, I need to perform inverse transformation on gaf matrix. Is there any way that could help me do that ?

**Comment by johannfaouzi** [comment]
Hi,

I'm not sure that I understand your question. The inverse transformation on any GAF matrix will be the original time series, which is needed to obtain the GAF matrix.

However, let's say that somehow you have a GAF matrix without the original time series. Here are the equations:
![GAF](https://user-images.githubusercontent.com/17053934/68192356-7ba1b400-ffb1-11e9-9bc7-32d41fdf5a76.png)
where:
![polar](https://user-images.githubusercontent.com/17053934/68192528-bc99c880-ffb1-11e9-98f3-1a9a198bb0a5.png)

By taking the `arccos` of the GASF matrix or the `arcsin` of the GADF matrix, you will obtain a system of linear equations with:
* `n*n` equations (each element of the matrix),
* `n` variables (each `phi_i`)

If your matrix is a GASF or a GADF, there will be a unique solution. Once you have obtained each `phi_i`, you can take the `cos` and obtain a time series that will be scaled in [-1, 1].

Let me know if this answers your question.

**Comment by johannfaouzi** [comment]
Closing for lack of response, feel free to reopen if necessary.
