### ISSUE TITLE
Setup.py missing comma

### ISSUE THREAD

**Issue by lucailvec** [johannfaouzi/pyts#65]
There are 2 problems.
The first one is the misalign of the documentation (https://pyts.readthedocs.io/en/latest/) that point to latest commit and the version on conda and pip still at 0.10 (while latest is the 0.11).
Maybe it is not a problem but i think it usefull if docs are sync with the package.

The second problem is the _setup.py_ of the repository.
At the line 18 there is:
```python
INSTALL_REQUIRES = ['numpy>=1.15.4'
                    'scipy>=1.3.0'
                    'scikit-learn>=0.22.1'
                    'joblib>=0.12'
                    'numba==0.46.0']
```

It missing some comma and as result when doing some `pip install -e .` it doesn't work...

It must be replaced simply with:

```python
INSTALL_REQUIRES = ['numpy>=1.15.4',
                    'scipy>=1.3.0',
                    'scikit-learn>=0.22.1',
                    'joblib>=0.12',
                    'numba==0.46.0']
```

Thank you

**Comment by johannfaouzi** [comment]
Thanks for the report!

* Regarding the documentation, the default version on RTD is `stable` (i.e. the latest released version, which is 0.10.0) : https://pyts.readthedocs.io/ will redirect to https://pyts.readthedocs.io/en/stable/. But you are right, the links are wrong in the README.

* Regarding the INSTALL_REQUIRES list, you are right (and these commas have been missing forever I think...).

I will fix this right now.
