### ISSUE TITLE
Variable Length

### ISSUE THREAD

**Issue by rymoore** [johannfaouzi/pyts#75]
In the documentation, [it is specified that most algorithms only work with fixed-length sequences](https://pyts.readthedocs.io/en/stable/introduction.html#challenge-lengths-of-time-series). What is the recommended approach for dealing with Multichannel time series event classification using samples with variable length? Zero padding perhaps?

**Comment by johannfaouzi** [comment]
Hi,

Zero padding smaller (or truncating longer) time series could be an option, although it might not be optimal. One limitation with the literature on time series classification is that articles use data from the [UCR Time Series Classification Repository](http://www.timeseriesclassification.com) which contained only fixed-length time series dataset for a very long time, and thus many algorithms make the assumption that a column / feature corresponds to the same timestamp for all the time series.

I don't know which algorithms you would like to try, but you might have better luck with other Python packages such as [tslearn](https://github.com/tslearn-team/tslearn) or [sktime](https://github.com/alan-turing-institute/sktime) which can deal with variable-length time series datasets.

I hope this helps you a bit.

**Comment by rymoore** [comment]
That's about what I expected - thanks @johannfaouzi
