### ISSUE TITLE
Error executing MTF example

### ISSUE THREAD

**Issue by AvisP** [johannfaouzi/pyts#9]
Hi,

I was running the for Markov Transition Field example and getting the following error

<code> X_mtf = mtf.transform(X)
D:\Anaconda3\envs\tf-gpu4\lib\site-packages\pyts\image\image.py:321: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  MTF[np.meshgrid(list_values[i], list_values[j])] = MTM[i, j]
Traceback (most recent call last):

  File "<ipython-input-26-d2810ef1637f>", line 1, in <module>
    X_mtf = mtf.transform(X)

  File "D:\Anaconda3\envs\tf-gpu4\lib\site-packages\pyts\image\image.py", line 301, in transform
    remainder)

  File "D:\Anaconda3\envs\tf-gpu4\lib\site-packages\numpy\lib\shape_base.py", line 357, in apply_along_axis
    res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))

  File "D:\Anaconda3\envs\tf-gpu4\lib\site-packages\pyts\image\image.py", line 336, in _mtf
    np.arange(start[j], end[j])].mean()

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (4,) (5,) </code>

GASF and GADF example worked fine. Kindly assist.

Regards,
Avi

**Comment by johannfaouzi** [comment]
Hi Avi,

Thanks for the report! Indeed there is a bug in the code below:
https://github.com/johannfaouzi/pyts/blob/0ea3dd26286ac817b26870e4348a1eef986c0007/pyts/image/image.py#L335-L336

It doesn't do what I had in mind what I coded this. It's a good thing that it `raised` an error because the results would be wrong. It should be:
```python
AMTF[i, j] = MTF[start[i]:end[i], start[j]:end[j]].mean()
```
It takes the mean value over a rectangle whose indices are bouded by `start[i]` and `end[i]` for the first axis and `start[j]` and `end[j]` for the second axis. The current code would only take the mean over the "diagonale" (which only works if the rectangle is a square, thus the error).

Would you like to submit a PR?

Best regards,
Johann

**Comment by AvisP** [comment]
Hi Johann,

I am new to github, do not know how to create pull requests and stuff. 

Please make the necessary changes and I will download your updated code. If you want to tag me for figuring out the bug please feel free to do so. It will be my first. :-)  

Thank You.

Best Regards,
Avi

**Comment by johannfaouzi** [comment]
To be honest, I don't know much about git and GitHub :)

The most important is whether you want to do it or not. Here's a little tutorial (you can do everything in your web browser):
1. Fork pyts (upper right corner). You should see pyts in your repositories.
2. In your forked version of pyts (https://github.com/AvisP/pyts), go to pyts/image/image.py, click on "Edit the file" and change the code at line 335-336. Commit the changes.
3. On the main page of your forked version, click on "Create a new pull request". You don't have to changes the branches, it should be both master by default. In the title of your PR, use #9 to refer to this issue.
4. You should be done. You'll see some tests running for the continuous integration, but if they now fail, it means that I messed up very badly when I coded those tests.

If you don't want to do it, just say no, it's totally fine!

Best regards,
Johann

**Comment by AvisP** [comment]
Hi Johann,

Thanks for the detailed guide! I made the changes and it successfully integrated. :-).

Best Regards,
Avishek Paul

**Comment by johannfaouzi** [comment]
Thank you!
